# Generated by Django 4.2.1 on 2023-11-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departmentID", models.CharField(default="N/A", max_length=100)),
                ("departmentName", models.CharField(default="N/A", max_length=100)),
                ("enrollment", models.CharField(default="N/A", max_length=100)),
                ("chineseStandard", models.CharField(default="N/A", max_length=100)),
                ("chineseRate", models.CharField(default="N/A", max_length=100)),
                ("englishStandard", models.CharField(default="N/A", max_length=100)),
                ("englishRate", models.CharField(default="N/A", max_length=100)),
                ("mathAStandard", models.CharField(default="N/A", max_length=100)),
                ("mathARate", models.CharField(default="N/A", max_length=100)),
                ("mathBStandard", models.CharField(default="N/A", max_length=100)),
                ("mathBRate", models.CharField(default="N/A", max_length=100)),
                ("socialStandard", models.CharField(default="N/A", max_length=100)),
                ("socialRate", models.CharField(default="N/A", max_length=100)),
                ("scienceStandard", models.CharField(default="N/A", max_length=100)),
                ("scienceRate", models.CharField(default="N/A", max_length=100)),
                ("addtionStandard", models.CharField(default="N/A", max_length=100)),
                ("addtionRate", models.CharField(default="N/A", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("universityID", models.CharField(default="N/A", max_length=100)),
                ("universityName", models.CharField(default="N/A", max_length=100)),
            ],
        ),
    ]
