# Generated by Django 4.2.1 on 2023-11-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applyAPP", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="EnglishListeningStandard",
            field=models.CharField(default="N/A", max_length=100),
        ),
    ]
